# Generated by Django 6.0.7 on 2026-08-08 19:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('description', models.TextField(default='', verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='السعر')),
                ('image', models.ImageField(upload_to='products/', verbose_name='صورة المنتج')),
                ('category', models.CharField(choices=[('wedding', 'دعوة زفاف'), ('engagement', 'دعوة خطوبة'), ('birthday', 'عيد ميلاد'), ('graduation', 'دعوة تخرج'), ('other', 'مناسبات أخرى')], default='wedding', max_length=20, verbose_name='نوع المناسبة')),
                ('is_active', models.BooleanField(default=True, verbose_name='متفعل؟')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
            },
        ),
    ]
