# Generated by Django 6.0.7 on 2026-08-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_invites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
